src/Entity/Orden.php
<?php

namespace App\Entity;

use App\Repository\OrdenRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrdenRepository::class)
 */
class Orden
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_empleado;

    /**
     * @ORM\Column(type="bigint")
     */
    private $total_orden;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdEmpleado(): ?int
    {
        return $this->id_empleado;
    }

    public function setIdEmpleado(int $id_empleado): self
    {
        $this->id_empleado = $id_empleado;

        return $this;
    }

    public function getTotalOrden(): ?string
    {
        return $this->total_orden;
    }

    public function setTotalOrden(string $total_orden): self
    {
        $this->total_orden = $total_orden;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }
}

src/Form/OrdenType.php
<?php

namespace App\Form;

use App\Entity\Orden;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrdenType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_empleado')
            ->add('total_orden')
            ->add('estado')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Orden::class,
        ]);
    }
}

src/Controller/OrdenController.php
<?php

namespace App\Controller;

use App\Entity\Orden;
use App\Form\OrdenType;
use App\Repository\OrdenRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/orden")
 */
class OrdenController extends AbstractController
{
    /**
     * @Route("/", name="orden_index", methods={"GET"})
     */
    public function index(OrdenRepository $ordenRepository): Response
    {
        return $this->render('orden/index.html.twig', [
            'ordens' => $ordenRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="orden_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $orden = new Orden();
        $form = $this->createForm(OrdenType::class, $orden);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($orden);
            $entityManager->flush();

            return $this->redirectToRoute('orden_index');
        }

        return $this->render('orden/new.html.twig', [
            'orden' => $orden,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="orden_show", methods={"GET"})
     */
    public function show(Orden $orden): Response
    {
        return $this->render('orden/show.html.twig', [
            'orden' => $orden,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="orden_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Orden $orden): Response
    {
        $form = $this->createForm(OrdenType::class, $orden);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('orden_index');
        }

        return $this->render('orden/edit.html.twig', [
            'orden' => $orden,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="orden_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Orden $orden): Response
    {
        if ($this->isCsrfTokenValid('delete'.$orden->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($orden);
            $entityManager->flush();
        }

        return $this->redirectToRoute('orden_index');
    }
}

templates/orden/_delete_form.html.twig
<form method="post" action="{{ path('orden_delete', {'id': orden.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ orden.id) }}">
    <button class="btn">Delete</button>
</form>

templates/orden/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/orden/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Orden{% endblock %}

{% block body %}
    <h1>Edit Orden</h1>

    {{ include('orden/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('orden_index') }}">back to list</a>

    {{ include('orden/_delete_form.html.twig') }}
{% endblock %}

templates/orden/index.html.twig
{% extends 'dash_board/index.html.twig' %}

{% block title %}Orden{% endblock %}

{% block vista_modulo %}
<h1 style="text-align: center;">Ordenes</h1>
    <table class="table table-bordered" style="text-align: center;">
        <thead>
            <tr>
                <th>Id Empleado</th>
                <th>Total Orden</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for orden in ordens %}
            <tr>
                <td>{{ orden.idEmpleado }}</td>
                <td>{{ orden.totalOrden }}</td>
                <td>{{ orden.estado }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('orden_show', {'id': orden.id}) }}"><span
                                class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;&nbsp;Editar</a>
                    <a class="btn btn-danger" href="{{ path('orden_edit', {'id': orden.id}) }}"><span
                                class="glyphicon glyphicon-trash"></span>&nbsp;&nbsp;&nbsp;Eliminar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">No hay registros creados</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/orden/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Orden{% endblock %}

{% block body %}
    <h1>Create new Orden</h1>

    {{ include('orden/_form.html.twig') }}

    <a href="{{ path('orden_index') }}">back to list</a>
{% endblock %}

templates/orden/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orden{% endblock %}

{% block body %}
    <h1>Orden</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ orden.id }}</td>
            </tr>
            <tr>
                <th>Id_empleado</th>
                <td>{{ orden.idEmpleado }}</td>
            </tr>
            <tr>
                <th>Total_orden</th>
                <td>{{ orden.totalOrden }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ orden.estado }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('orden_index') }}">back to list</a>

    <a href="{{ path('orden_edit', {'id': orden.id}) }}">edit</a>

    {{ include('orden/_delete_form.html.twig') }}
{% endblock %}